version: "3.7"
services:
  elasticsearch:
    image: elasticsearch:8.12.2
    environment:
      discovery.type: single-node
    hostname: elasticsearch
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
  docstore:
    image: quarkus-nosql-tests/docstore-elasticsearch:1.0-SNAPSHOT
    depends_on:
      - elasticsearch
    hostname: docstore
    container_name: docstore
    links:
      - elasticsearch:elasticsearch
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      JAVA_DEBUG: "true"
      JAVA_APP_DIR: /home/jboss
      JAVA_APP_JAR: quarkus-run.jar


